// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBr1NQFVZXyVYAD2Hayr7isOfMLOKlYZIE',
    appId: '1:619789450816:web:3e4c07c9c7800ac2e869a5',
    messagingSenderId: '619789450816',
    projectId: 'laundry-management-syste-39ec1',
    authDomain: 'laundry-management-syste-39ec1.firebaseapp.com',
    storageBucket: 'laundry-management-syste-39ec1.firebasestorage.app',
    measurementId: 'G-TBM1V28ZSR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNEVpNdZqDWDGwMtseDOi25XD7fvECY5U',
    appId: '1:619789450816:android:5c36347044bde2afe869a5',
    messagingSenderId: '619789450816',
    projectId: 'laundry-management-syste-39ec1',
    storageBucket: 'laundry-management-syste-39ec1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLWERb-kLWO3eDKOq5mG5x9Ct92YK5abQ',
    appId: '1:619789450816:ios:2266d82585d0d2c1e869a5',
    messagingSenderId: '619789450816',
    projectId: 'laundry-management-syste-39ec1',
    storageBucket: 'laundry-management-syste-39ec1.firebasestorage.app',
    iosBundleId: 'com.example.laundryFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLWERb-kLWO3eDKOq5mG5x9Ct92YK5abQ',
    appId: '1:619789450816:ios:2266d82585d0d2c1e869a5',
    messagingSenderId: '619789450816',
    projectId: 'laundry-management-syste-39ec1',
    storageBucket: 'laundry-management-syste-39ec1.firebasestorage.app',
    iosBundleId: 'com.example.laundryFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBr1NQFVZXyVYAD2Hayr7isOfMLOKlYZIE',
    appId: '1:619789450816:web:5f59d2640665eaeee869a5',
    messagingSenderId: '619789450816',
    projectId: 'laundry-management-syste-39ec1',
    authDomain: 'laundry-management-syste-39ec1.firebaseapp.com',
    storageBucket: 'laundry-management-syste-39ec1.firebasestorage.app',
    measurementId: 'G-LWM0HYF7F3',
  );
}
